#!/usr/bin/env bash

# set -x

JS_BOILERPLATE_SOURCE='https://codeload.github.com/nhandyal/js-boilerplate/zip/master'
JS_BOILERPLATE_ZIP='/tmp/js_boilerplate.zip'
TEMP_DIR='/tmp/jsb'


curl -o "$JS_BOILERPLATE_ZIP" "$JS_BOILERPLATE_SOURCE"
unzip -d "$TEMP_DIR" "$JS_BOILERPLATE_ZIP"

shopt -s dotglob
mv -v "$TEMP_DIR"/js-boilerplate-master/* ./

rm -rf "$TEMP_DIR" "$JS_BOILERPLATE_ZIP"